image: Visual Studio 2019
install:
  - cinst fake
build_script:
  # See https://stackoverflow.com/a/12866669/1269722
  - cmd: fake.exe run build.fsx --parallel 3
test: off
environment:
  PAKET_BOOTSTRAPPER_TRACE: true
pull_requests:
  do_not_increment_build_number: true
nuget:
  disable_publish_on_pr: true
  disable_publish_octopus: true
artifacts:
  - path: 'src\PCSC\bin\Release\*.nupkg'
    type: NuGetPackage
  - path: 'src\PCSC.Iso7816\bin\Release\*.nupkg'
    type: NuGetPackage
  - path: 'src\PCSC.Reactive\bin\Release\*.nupkg'
    type: Zip